/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/astronaut.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Astronaut(props) {
  const { nodes, materials } = useGLTF('./models/astronaut.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CHAR_Cooper001.geometry} material={materials.MAT_CHAR_Cooper_Head} />
        <mesh geometry={nodes.CHAR_Cooper002.geometry} material={materials.MAT_CHAR_Cooper_Body} />
        <mesh geometry={nodes.CHAR_Cooper003.geometry} material={materials.Glass} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/astronaut.glb')
