/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/yoda.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Yoda(props) {
  const { nodes, materials } = useGLTF('./models/yoda.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BY_fur.geometry} material={materials.fur} scale={0.01} />
      <group scale={0.01}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.skin} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.nail} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials.eyes_w} />
        <mesh geometry={nodes.Mesh001_3.geometry} material={materials.eyes_b} />
        <mesh geometry={nodes.Mesh001_4.geometry} material={materials.pupil} />
        <mesh geometry={nodes.Mesh001_5.geometry} material={materials.lens} />
        <mesh geometry={nodes.Mesh001_6.geometry} material={materials.oral} />
      </group>
      <mesh geometry={nodes.cloth_shape_001.geometry} material={materials.BY_cloth3} scale={0.01} />
      <group scale={0.01}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials.BY_cloth1} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.BY_cloth2} />
      </group>
      <mesh geometry={nodes.cloth_shape_003.geometry} material={materials.BY_cloth4} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./models/yoda.glb')
